### ISSUE TITLE
Fix the repo structure for the GitHub deployment actions

### ISSUE THREAD

**Issue by ChrisHardie** [10up/simple-new-post-emails#24]
I've been working with @jeffpaul and indirectly @helen to get the GitHub deploy actions working for this repo. We noticed they [weren't working in May](https://github.com/10up/simple-new-post-emails/actions/runs/110521134) and thought it was related to the way it was added after the assets directory (see #17 #18). 

It [failed again](https://github.com/10up/simple-new-post-emails/runs/972532920?check_suite_focus=true) when trying to update the readme for 5.5 tested up to, at which point Helen noted:

```
Sounds like issue is its removing CHANGELOG.md, LICENSE, and everything in assets which is correct behavior but also means it’s failing
Would need to manually remove those first and then it can run
the best thing to do is to do a manual commit removing those files
And then probably change the repo to use .wordpress-org instead of assets for consistency, then it will run
And that way it will work in the future 
```

Today I tried various and silly combinations of removing and restructuring things (see #20 #21 #22 #23) and I'm still having issues. Now, if the action runs and `.wordpress-org` is present in the repo, there’s an error saying “Other files have been modified; changes not deployed” - see https://github.com/10up/simple-new-post-emails/runs/1014001024?check_suite_focus=true

But if `.wordpress-org` is not present, there’s an error saying “rsync: change_dir “/github/workspace/.wordpress-org” failed: No such file or directory (2)” - see https://github.com/10up/simple-new-post-emails/runs/1014019760?check_suite_focus=true

I need to dive more into what the action is doing and what it needs to be successful, so I can pick that back up soon. Any guidance or suggestions will of course be appreciated. And I think I owe 10up some GitHub build minutes. :)

**Comment by helen** [comment]
Build minutes are free for open source :) In any case, it looks like what you need to do here is add `/.wordpress-org export-ignore` to `.gitattributes`. `.gitattributes` needs to reflect anything that's excluded from being deployed to .org; previously the failures were because things like `LICENSE` and `CHANGELOG.md` are in there so when it checked against what was going to be synced, those were being deleted and that was counted as a non-readme/asset change, which is technically correct because the action does not differentiate between filetypes. You should be able to restore those other files to GitHub now as well, since they've been deleted in SVN in the meantime (I think by another action run?).

**Comment by ChrisHardie** [comment]
Current status: successful action runs abound, ending in "Nothing to deploy!" and so SVN repo is slightly out of date but not in any user-facing way. When an actual change is next deployed, I expect everything will be all synced up.
